# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageWindow(object):
    def setupUi(self, ManageWindow):
        ManageWindow.setObjectName("ManageWindow")
        ManageWindow.resize(551, 143)
        ManageWindow.setMinimumSize(QtCore.QSize(551, 143))
        ManageWindow.setMaximumSize(QtCore.QSize(551, 143))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imagenes/manager.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ManageWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ManageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnIniciarObservable = QtWidgets.QPushButton(self.centralwidget)
        self.btnIniciarObservable.setGeometry(QtCore.QRect(30, 30, 151, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnIniciarObservable.sizePolicy().hasHeightForWidth())
        self.btnIniciarObservable.setSizePolicy(sizePolicy)
        self.btnIniciarObservable.setMinimumSize(QtCore.QSize(151, 81))
        self.btnIniciarObservable.setMaximumSize(QtCore.QSize(151, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.btnIniciarObservable.setFont(font)
        self.btnIniciarObservable.setAutoFillBackground(False)
        self.btnIniciarObservable.setObjectName("btnIniciarObservable")
        self.btnIniciarObservador = QtWidgets.QPushButton(self.centralwidget)
        self.btnIniciarObservador.setGeometry(QtCore.QRect(200, 30, 151, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.btnIniciarObservador.setFont(font)
        self.btnIniciarObservador.setObjectName("btnIniciarObservador")
        self.btnTerminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnTerminar.setGeometry(QtCore.QRect(370, 30, 151, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.btnTerminar.setFont(font)
        self.btnTerminar.setObjectName("btnTerminar")
        ManageWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManageWindow)
        QtCore.QMetaObject.connectSlotsByName(ManageWindow)

    def retranslateUi(self, ManageWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageWindow.setWindowTitle(_translate("ManageWindow", "Manage"))
        self.btnIniciarObservable.setText(_translate("ManageWindow", "Iniciar\n"
"Observable"))
        self.btnIniciarObservador.setText(_translate("ManageWindow", "Iniciar\n"
"Observador"))
        self.btnTerminar.setText(_translate("ManageWindow", "Terminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManageWindow = QtWidgets.QMainWindow()
    ui = Ui_ManageWindow()
    ui.setupUi(ManageWindow)
    ManageWindow.show()
    sys.exit(app.exec_())
