# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'observable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Observable(object):
    def setupUi(self, Observable):
        Observable.setObjectName("Observable")
        Observable.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Observable.sizePolicy().hasHeightForWidth())
        Observable.setSizePolicy(sizePolicy)
        Observable.setMinimumSize(QtCore.QSize(400, 200))
        Observable.setMaximumSize(QtCore.QSize(400, 200))
        Observable.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imagenes/manager.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Observable.setWindowIcon(icon)
        self.lbl_state = QtWidgets.QLabel(Observable)
        self.lbl_state.setGeometry(QtCore.QRect(40, 20, 311, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.lbl_state.setFont(font)
        self.lbl_state.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_state.setObjectName("lbl_state")
        self.lbl_count = QtWidgets.QLabel(Observable)
        self.lbl_count.setGeometry(QtCore.QRect(40, 80, 311, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.lbl_count.setFont(font)
        self.lbl_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_count.setObjectName("lbl_count")
        self.btn_update = QtWidgets.QPushButton(Observable)
        self.btn_update.setGeometry(QtCore.QRect(70, 140, 261, 31))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.btn_update.setFont(font)
        self.btn_update.setObjectName("btn_update")

        self.retranslateUi(Observable)
        QtCore.QMetaObject.connectSlotsByName(Observable)

    def retranslateUi(self, Observable):
        _translate = QtCore.QCoreApplication.translate
        Observable.setWindowTitle(_translate("Observable", "Observable"))
        self.lbl_state.setText(_translate("Observable", "TextLabel"))
        self.lbl_count.setText(_translate("Observable", "TextLabel"))
        self.btn_update.setText(_translate("Observable", "Update Temperatura"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Observable = QtWidgets.QDialog()
    ui = Ui_Observable()
    ui.setupUi(Observable)
    Observable.show()
    sys.exit(app.exec_())
